with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
packages:
  booker/modules/users/domain/interfaces:
    interfaces:
      UserRepository:
      UserService:
      TokenService:
  booker/modules/wallet/domain/interfaces:
    interfaces:
      WalletRepository:
      WalletService:
  booker/modules/order/domain/interfaces:
    interfaces:
      OrderRepository:
      OrderService:
      WalletClient:
      MatchingClient:
  booker/modules/matching/domain/interfaces:
    interfaces:
      TradeRepository:
      MatchingService:
      WalletClient:
        config:
          mockname: MockMatchingWalletClient
      OrderClient:
  booker/modules/notification/domain/interfaces:
    interfaces:
      NotificationRepository:
      NotificationService:
      Broadcaster:
