with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
packages:
  booker/modules/users/domain/interfaces:
    interfaces:
      UserRepository:
      UserService:
      TokenService:
  booker/modules/wallet/domain/interfaces:
    interfaces:
      WalletRepository:
      WalletService:
