// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "booker/modules/notification/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockNotificationRepository is an autogenerated mock type for the NotificationRepository type
type MockNotificationRepository struct {
	mock.Mock
}

type MockNotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationRepository) EXPECT() *MockNotificationRepository_Expecter {
	return &MockNotificationRepository_Expecter{mock: &_m.Mock}
}

// CountUnread provides a mock function with given fields: ctx, userID
func (_m *MockNotificationRepository) CountUnread(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUnread")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_CountUnread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUnread'
type MockNotificationRepository_CountUnread_Call struct {
	*mock.Call
}

// CountUnread is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockNotificationRepository_Expecter) CountUnread(ctx interface{}, userID interface{}) *MockNotificationRepository_CountUnread_Call {
	return &MockNotificationRepository_CountUnread_Call{Call: _e.mock.On("CountUnread", ctx, userID)}
}

func (_c *MockNotificationRepository_CountUnread_Call) Run(run func(ctx context.Context, userID string)) *MockNotificationRepository_CountUnread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNotificationRepository_CountUnread_Call) Return(_a0 int64, _a1 error) *MockNotificationRepository_CountUnread_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_CountUnread_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockNotificationRepository_CountUnread_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, n
func (_m *MockNotificationRepository) Create(ctx context.Context, n *entities.Notification) (bool, error) {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Notification) (bool, error)); ok {
		return rf(ctx, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Notification) bool); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Notification) error); ok {
		r1 = rf(ctx, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNotificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - n *entities.Notification
func (_e *MockNotificationRepository_Expecter) Create(ctx interface{}, n interface{}) *MockNotificationRepository_Create_Call {
	return &MockNotificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, n)}
}

func (_c *MockNotificationRepository_Create_Call) Run(run func(ctx context.Context, n *entities.Notification)) *MockNotificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Notification))
	})
	return _c
}

func (_c *MockNotificationRepository_Create_Call) Return(_a0 bool, _a1 error) *MockNotificationRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.Notification) (bool, error)) *MockNotificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID, cursor, limit, onlyUnread
func (_m *MockNotificationRepository) ListByUser(ctx context.Context, userID string, cursor time.Time, limit int32, onlyUnread bool) ([]*entities.Notification, error) {
	ret := _m.Called(ctx, userID, cursor, limit, onlyUnread)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*entities.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, int32, bool) ([]*entities.Notification, error)); ok {
		return rf(ctx, userID, cursor, limit, onlyUnread)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, int32, bool) []*entities.Notification); ok {
		r0 = rf(ctx, userID, cursor, limit, onlyUnread)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, int32, bool) error); ok {
		r1 = rf(ctx, userID, cursor, limit, onlyUnread)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockNotificationRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - cursor time.Time
//   - limit int32
//   - onlyUnread bool
func (_e *MockNotificationRepository_Expecter) ListByUser(ctx interface{}, userID interface{}, cursor interface{}, limit interface{}, onlyUnread interface{}) *MockNotificationRepository_ListByUser_Call {
	return &MockNotificationRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, cursor, limit, onlyUnread)}
}

func (_c *MockNotificationRepository_ListByUser_Call) Run(run func(ctx context.Context, userID string, cursor time.Time, limit int32, onlyUnread bool)) *MockNotificationRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(int32), args[4].(bool))
	})
	return _c
}

func (_c *MockNotificationRepository_ListByUser_Call) Return(_a0 []*entities.Notification, _a1 error) *MockNotificationRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_ListByUser_Call) RunAndReturn(run func(context.Context, string, time.Time, int32, bool) ([]*entities.Notification, error)) *MockNotificationRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllAsRead provides a mock function with given fields: ctx, userID
func (_m *MockNotificationRepository) MarkAllAsRead(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllAsRead")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_MarkAllAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllAsRead'
type MockNotificationRepository_MarkAllAsRead_Call struct {
	*mock.Call
}

// MarkAllAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockNotificationRepository_Expecter) MarkAllAsRead(ctx interface{}, userID interface{}) *MockNotificationRepository_MarkAllAsRead_Call {
	return &MockNotificationRepository_MarkAllAsRead_Call{Call: _e.mock.On("MarkAllAsRead", ctx, userID)}
}

func (_c *MockNotificationRepository_MarkAllAsRead_Call) Run(run func(ctx context.Context, userID string)) *MockNotificationRepository_MarkAllAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNotificationRepository_MarkAllAsRead_Call) Return(_a0 int64, _a1 error) *MockNotificationRepository_MarkAllAsRead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_MarkAllAsRead_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockNotificationRepository_MarkAllAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsRead provides a mock function with given fields: ctx, id, userID
func (_m *MockNotificationRepository) MarkAsRead(ctx context.Context, id string, userID string) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationRepository_MarkAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsRead'
type MockNotificationRepository_MarkAsRead_Call struct {
	*mock.Call
}

// MarkAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockNotificationRepository_Expecter) MarkAsRead(ctx interface{}, id interface{}, userID interface{}) *MockNotificationRepository_MarkAsRead_Call {
	return &MockNotificationRepository_MarkAsRead_Call{Call: _e.mock.On("MarkAsRead", ctx, id, userID)}
}

func (_c *MockNotificationRepository_MarkAsRead_Call) Run(run func(ctx context.Context, id string, userID string)) *MockNotificationRepository_MarkAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNotificationRepository_MarkAsRead_Call) Return(_a0 error) *MockNotificationRepository_MarkAsRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationRepository_MarkAsRead_Call) RunAndReturn(run func(context.Context, string, string) error) *MockNotificationRepository_MarkAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationRepository creates a new instance of MockNotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationRepository {
	mock := &MockNotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
