// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dto "booker/modules/notification/application/dto"
	entities "booker/modules/notification/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNotificationService is an autogenerated mock type for the NotificationService type
type MockNotificationService struct {
	mock.Mock
}

type MockNotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationService) EXPECT() *MockNotificationService_Expecter {
	return &MockNotificationService_Expecter{mock: &_m.Mock}
}

// CountUnread provides a mock function with given fields: ctx, userID
func (_m *MockNotificationService) CountUnread(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUnread")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationService_CountUnread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUnread'
type MockNotificationService_CountUnread_Call struct {
	*mock.Call
}

// CountUnread is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockNotificationService_Expecter) CountUnread(ctx interface{}, userID interface{}) *MockNotificationService_CountUnread_Call {
	return &MockNotificationService_CountUnread_Call{Call: _e.mock.On("CountUnread", ctx, userID)}
}

func (_c *MockNotificationService_CountUnread_Call) Run(run func(ctx context.Context, userID string)) *MockNotificationService_CountUnread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNotificationService_CountUnread_Call) Return(_a0 int64, _a1 error) *MockNotificationService_CountUnread_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationService_CountUnread_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockNotificationService_CountUnread_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNotification provides a mock function with given fields: ctx, n
func (_m *MockNotificationService) CreateNotification(ctx context.Context, n *entities.Notification) (bool, error) {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Notification) (bool, error)); ok {
		return rf(ctx, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Notification) bool); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Notification) error); ok {
		r1 = rf(ctx, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationService_CreateNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotification'
type MockNotificationService_CreateNotification_Call struct {
	*mock.Call
}

// CreateNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - n *entities.Notification
func (_e *MockNotificationService_Expecter) CreateNotification(ctx interface{}, n interface{}) *MockNotificationService_CreateNotification_Call {
	return &MockNotificationService_CreateNotification_Call{Call: _e.mock.On("CreateNotification", ctx, n)}
}

func (_c *MockNotificationService_CreateNotification_Call) Run(run func(ctx context.Context, n *entities.Notification)) *MockNotificationService_CreateNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Notification))
	})
	return _c
}

func (_c *MockNotificationService_CreateNotification_Call) Return(_a0 bool, _a1 error) *MockNotificationService_CreateNotification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationService_CreateNotification_Call) RunAndReturn(run func(context.Context, *entities.Notification) (bool, error)) *MockNotificationService_CreateNotification_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotifications provides a mock function with given fields: ctx, userID, req
func (_m *MockNotificationService) ListNotifications(ctx context.Context, userID string, req *dto.ListNotificationsDTO) ([]*entities.Notification, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for ListNotifications")
	}

	var r0 []*entities.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.ListNotificationsDTO) ([]*entities.Notification, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.ListNotificationsDTO) []*entities.Notification); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.ListNotificationsDTO) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationService_ListNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotifications'
type MockNotificationService_ListNotifications_Call struct {
	*mock.Call
}

// ListNotifications is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *dto.ListNotificationsDTO
func (_e *MockNotificationService_Expecter) ListNotifications(ctx interface{}, userID interface{}, req interface{}) *MockNotificationService_ListNotifications_Call {
	return &MockNotificationService_ListNotifications_Call{Call: _e.mock.On("ListNotifications", ctx, userID, req)}
}

func (_c *MockNotificationService_ListNotifications_Call) Run(run func(ctx context.Context, userID string, req *dto.ListNotificationsDTO)) *MockNotificationService_ListNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*dto.ListNotificationsDTO))
	})
	return _c
}

func (_c *MockNotificationService_ListNotifications_Call) Return(_a0 []*entities.Notification, _a1 error) *MockNotificationService_ListNotifications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationService_ListNotifications_Call) RunAndReturn(run func(context.Context, string, *dto.ListNotificationsDTO) ([]*entities.Notification, error)) *MockNotificationService_ListNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllAsRead provides a mock function with given fields: ctx, userID
func (_m *MockNotificationService) MarkAllAsRead(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllAsRead")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationService_MarkAllAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllAsRead'
type MockNotificationService_MarkAllAsRead_Call struct {
	*mock.Call
}

// MarkAllAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockNotificationService_Expecter) MarkAllAsRead(ctx interface{}, userID interface{}) *MockNotificationService_MarkAllAsRead_Call {
	return &MockNotificationService_MarkAllAsRead_Call{Call: _e.mock.On("MarkAllAsRead", ctx, userID)}
}

func (_c *MockNotificationService_MarkAllAsRead_Call) Run(run func(ctx context.Context, userID string)) *MockNotificationService_MarkAllAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNotificationService_MarkAllAsRead_Call) Return(_a0 int64, _a1 error) *MockNotificationService_MarkAllAsRead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationService_MarkAllAsRead_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockNotificationService_MarkAllAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsRead provides a mock function with given fields: ctx, id, userID
func (_m *MockNotificationService) MarkAsRead(ctx context.Context, id string, userID string) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationService_MarkAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsRead'
type MockNotificationService_MarkAsRead_Call struct {
	*mock.Call
}

// MarkAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockNotificationService_Expecter) MarkAsRead(ctx interface{}, id interface{}, userID interface{}) *MockNotificationService_MarkAsRead_Call {
	return &MockNotificationService_MarkAsRead_Call{Call: _e.mock.On("MarkAsRead", ctx, id, userID)}
}

func (_c *MockNotificationService_MarkAsRead_Call) Run(run func(ctx context.Context, id string, userID string)) *MockNotificationService_MarkAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNotificationService_MarkAsRead_Call) Return(_a0 error) *MockNotificationService_MarkAsRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationService_MarkAsRead_Call) RunAndReturn(run func(context.Context, string, string) error) *MockNotificationService_MarkAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationService creates a new instance of MockNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationService {
	mock := &MockNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
