// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "booker/modules/notification/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockBroadcaster is an autogenerated mock type for the Broadcaster type
type MockBroadcaster struct {
	mock.Mock
}

type MockBroadcaster_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBroadcaster) EXPECT() *MockBroadcaster_Expecter {
	return &MockBroadcaster_Expecter{mock: &_m.Mock}
}

// SendToUser provides a mock function with given fields: userID, notification
func (_m *MockBroadcaster) SendToUser(userID string, notification *entities.Notification) {
	_m.Called(userID, notification)
}

// MockBroadcaster_SendToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendToUser'
type MockBroadcaster_SendToUser_Call struct {
	*mock.Call
}

// SendToUser is a helper method to define mock.On call
//   - userID string
//   - notification *entities.Notification
func (_e *MockBroadcaster_Expecter) SendToUser(userID interface{}, notification interface{}) *MockBroadcaster_SendToUser_Call {
	return &MockBroadcaster_SendToUser_Call{Call: _e.mock.On("SendToUser", userID, notification)}
}

func (_c *MockBroadcaster_SendToUser_Call) Run(run func(userID string, notification *entities.Notification)) *MockBroadcaster_SendToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*entities.Notification))
	})
	return _c
}

func (_c *MockBroadcaster_SendToUser_Call) Return() *MockBroadcaster_SendToUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBroadcaster_SendToUser_Call) RunAndReturn(run func(string, *entities.Notification)) *MockBroadcaster_SendToUser_Call {
	_c.Run(run)
	return _c
}

// NewMockBroadcaster creates a new instance of MockBroadcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBroadcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBroadcaster {
	mock := &MockBroadcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
