// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderClient is an autogenerated mock type for the OrderClient type
type MockOrderClient struct {
	mock.Mock
}

type MockOrderClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderClient) EXPECT() *MockOrderClient_Expecter {
	return &MockOrderClient_Expecter{mock: &_m.Mock}
}

// UpdateOrderFill provides a mock function with given fields: ctx, orderID, filledQty, status
func (_m *MockOrderClient) UpdateOrderFill(ctx context.Context, orderID string, filledQty decimal.Decimal, status string) error {
	ret := _m.Called(ctx, orderID, filledQty, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderFill")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, decimal.Decimal, string) error); ok {
		r0 = rf(ctx, orderID, filledQty, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderClient_UpdateOrderFill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderFill'
type MockOrderClient_UpdateOrderFill_Call struct {
	*mock.Call
}

// UpdateOrderFill is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - filledQty decimal.Decimal
//   - status string
func (_e *MockOrderClient_Expecter) UpdateOrderFill(ctx interface{}, orderID interface{}, filledQty interface{}, status interface{}) *MockOrderClient_UpdateOrderFill_Call {
	return &MockOrderClient_UpdateOrderFill_Call{Call: _e.mock.On("UpdateOrderFill", ctx, orderID, filledQty, status)}
}

func (_c *MockOrderClient_UpdateOrderFill_Call) Run(run func(ctx context.Context, orderID string, filledQty decimal.Decimal, status string)) *MockOrderClient_UpdateOrderFill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(decimal.Decimal), args[3].(string))
	})
	return _c
}

func (_c *MockOrderClient_UpdateOrderFill_Call) Return(_a0 error) *MockOrderClient_UpdateOrderFill_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderClient_UpdateOrderFill_Call) RunAndReturn(run func(context.Context, string, decimal.Decimal, string) error) *MockOrderClient_UpdateOrderFill_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderClient creates a new instance of MockOrderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderClient {
	mock := &MockOrderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
