// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "booker/modules/matching/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTradeRepository is an autogenerated mock type for the TradeRepository type
type MockTradeRepository struct {
	mock.Mock
}

type MockTradeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTradeRepository) EXPECT() *MockTradeRepository_Expecter {
	return &MockTradeRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, trade
func (_m *MockTradeRepository) Create(ctx context.Context, trade *entities.Trade) (*entities.Trade, error) {
	ret := _m.Called(ctx, trade)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Trade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Trade) (*entities.Trade, error)); ok {
		return rf(ctx, trade)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Trade) *entities.Trade); ok {
		r0 = rf(ctx, trade)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Trade)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Trade) error); ok {
		r1 = rf(ctx, trade)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTradeRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTradeRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - trade *entities.Trade
func (_e *MockTradeRepository_Expecter) Create(ctx interface{}, trade interface{}) *MockTradeRepository_Create_Call {
	return &MockTradeRepository_Create_Call{Call: _e.mock.On("Create", ctx, trade)}
}

func (_c *MockTradeRepository_Create_Call) Run(run func(ctx context.Context, trade *entities.Trade)) *MockTradeRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Trade))
	})
	return _c
}

func (_c *MockTradeRepository_Create_Call) Return(_a0 *entities.Trade, _a1 error) *MockTradeRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTradeRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.Trade) (*entities.Trade, error)) *MockTradeRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTradeRepository) GetByID(ctx context.Context, id string) (*entities.Trade, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Trade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Trade, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Trade); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Trade)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTradeRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTradeRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTradeRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTradeRepository_GetByID_Call {
	return &MockTradeRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTradeRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockTradeRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTradeRepository_GetByID_Call) Return(_a0 *entities.Trade, _a1 error) *MockTradeRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTradeRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*entities.Trade, error)) *MockTradeRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPair provides a mock function with given fields: ctx, pairID, limit, offset
func (_m *MockTradeRepository) ListByPair(ctx context.Context, pairID string, limit int32, offset int32) ([]*entities.Trade, error) {
	ret := _m.Called(ctx, pairID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByPair")
	}

	var r0 []*entities.Trade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) ([]*entities.Trade, error)); ok {
		return rf(ctx, pairID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) []*entities.Trade); ok {
		r0 = rf(ctx, pairID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Trade)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, int32) error); ok {
		r1 = rf(ctx, pairID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTradeRepository_ListByPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPair'
type MockTradeRepository_ListByPair_Call struct {
	*mock.Call
}

// ListByPair is a helper method to define mock.On call
//   - ctx context.Context
//   - pairID string
//   - limit int32
//   - offset int32
func (_e *MockTradeRepository_Expecter) ListByPair(ctx interface{}, pairID interface{}, limit interface{}, offset interface{}) *MockTradeRepository_ListByPair_Call {
	return &MockTradeRepository_ListByPair_Call{Call: _e.mock.On("ListByPair", ctx, pairID, limit, offset)}
}

func (_c *MockTradeRepository_ListByPair_Call) Run(run func(ctx context.Context, pairID string, limit int32, offset int32)) *MockTradeRepository_ListByPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *MockTradeRepository_ListByPair_Call) Return(_a0 []*entities.Trade, _a1 error) *MockTradeRepository_ListByPair_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTradeRepository_ListByPair_Call) RunAndReturn(run func(context.Context, string, int32, int32) ([]*entities.Trade, error)) *MockTradeRepository_ListByPair_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTradeRepository creates a new instance of MockTradeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTradeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTradeRepository {
	mock := &MockTradeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
