// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"
)

// MockMatchingWalletClient is an autogenerated mock type for the WalletClient type
type MockMatchingWalletClient struct {
	mock.Mock
}

type MockMatchingWalletClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchingWalletClient) EXPECT() *MockMatchingWalletClient_Expecter {
	return &MockMatchingWalletClient_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockMatchingWalletClient) Deposit(ctx context.Context, userID string, assetID string, amount decimal.Decimal) error {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchingWalletClient_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type MockMatchingWalletClient_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockMatchingWalletClient_Expecter) Deposit(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockMatchingWalletClient_Deposit_Call {
	return &MockMatchingWalletClient_Deposit_Call{Call: _e.mock.On("Deposit", ctx, userID, assetID, amount)}
}

func (_c *MockMatchingWalletClient_Deposit_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockMatchingWalletClient_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockMatchingWalletClient_Deposit_Call) Return(_a0 error) *MockMatchingWalletClient_Deposit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchingWalletClient_Deposit_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) error) *MockMatchingWalletClient_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// SettleTrade provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockMatchingWalletClient) SettleTrade(ctx context.Context, userID string, assetID string, amount decimal.Decimal) error {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for SettleTrade")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchingWalletClient_SettleTrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SettleTrade'
type MockMatchingWalletClient_SettleTrade_Call struct {
	*mock.Call
}

// SettleTrade is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockMatchingWalletClient_Expecter) SettleTrade(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockMatchingWalletClient_SettleTrade_Call {
	return &MockMatchingWalletClient_SettleTrade_Call{Call: _e.mock.On("SettleTrade", ctx, userID, assetID, amount)}
}

func (_c *MockMatchingWalletClient_SettleTrade_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockMatchingWalletClient_SettleTrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockMatchingWalletClient_SettleTrade_Call) Return(_a0 error) *MockMatchingWalletClient_SettleTrade_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchingWalletClient_SettleTrade_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) error) *MockMatchingWalletClient_SettleTrade_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchingWalletClient creates a new instance of MockMatchingWalletClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchingWalletClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchingWalletClient {
	mock := &MockMatchingWalletClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
