// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	engine "booker/modules/matching/engine"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMatchingService is an autogenerated mock type for the MatchingService type
type MockMatchingService struct {
	mock.Mock
}

type MockMatchingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchingService) EXPECT() *MockMatchingService_Expecter {
	return &MockMatchingService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, pairID, orderID
func (_m *MockMatchingService) CancelOrder(ctx context.Context, pairID string, orderID string) error {
	ret := _m.Called(ctx, pairID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, pairID, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchingService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockMatchingService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - pairID string
//   - orderID string
func (_e *MockMatchingService_Expecter) CancelOrder(ctx interface{}, pairID interface{}, orderID interface{}) *MockMatchingService_CancelOrder_Call {
	return &MockMatchingService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, pairID, orderID)}
}

func (_c *MockMatchingService_CancelOrder_Call) Run(run func(ctx context.Context, pairID string, orderID string)) *MockMatchingService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMatchingService_CancelOrder_Call) Return(_a0 error) *MockMatchingService_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchingService_CancelOrder_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMatchingService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderBook provides a mock function with given fields: ctx, pairID
func (_m *MockMatchingService) GetOrderBook(ctx context.Context, pairID string) (*engine.OrderBookSnapshot, error) {
	ret := _m.Called(ctx, pairID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderBook")
	}

	var r0 *engine.OrderBookSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*engine.OrderBookSnapshot, error)); ok {
		return rf(ctx, pairID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *engine.OrderBookSnapshot); ok {
		r0 = rf(ctx, pairID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*engine.OrderBookSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pairID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchingService_GetOrderBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderBook'
type MockMatchingService_GetOrderBook_Call struct {
	*mock.Call
}

// GetOrderBook is a helper method to define mock.On call
//   - ctx context.Context
//   - pairID string
func (_e *MockMatchingService_Expecter) GetOrderBook(ctx interface{}, pairID interface{}) *MockMatchingService_GetOrderBook_Call {
	return &MockMatchingService_GetOrderBook_Call{Call: _e.mock.On("GetOrderBook", ctx, pairID)}
}

func (_c *MockMatchingService_GetOrderBook_Call) Run(run func(ctx context.Context, pairID string)) *MockMatchingService_GetOrderBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMatchingService_GetOrderBook_Call) Return(_a0 *engine.OrderBookSnapshot, _a1 error) *MockMatchingService_GetOrderBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchingService_GetOrderBook_Call) RunAndReturn(run func(context.Context, string) (*engine.OrderBookSnapshot, error)) *MockMatchingService_GetOrderBook_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitOrder provides a mock function with given fields: ctx, order
func (_m *MockMatchingService) SubmitOrder(ctx context.Context, order *engine.BookOrder) ([]*engine.Trade, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SubmitOrder")
	}

	var r0 []*engine.Trade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *engine.BookOrder) ([]*engine.Trade, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *engine.BookOrder) []*engine.Trade); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*engine.Trade)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *engine.BookOrder) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchingService_SubmitOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitOrder'
type MockMatchingService_SubmitOrder_Call struct {
	*mock.Call
}

// SubmitOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *engine.BookOrder
func (_e *MockMatchingService_Expecter) SubmitOrder(ctx interface{}, order interface{}) *MockMatchingService_SubmitOrder_Call {
	return &MockMatchingService_SubmitOrder_Call{Call: _e.mock.On("SubmitOrder", ctx, order)}
}

func (_c *MockMatchingService_SubmitOrder_Call) Run(run func(ctx context.Context, order *engine.BookOrder)) *MockMatchingService_SubmitOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*engine.BookOrder))
	})
	return _c
}

func (_c *MockMatchingService_SubmitOrder_Call) Return(_a0 []*engine.Trade, _a1 error) *MockMatchingService_SubmitOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchingService_SubmitOrder_Call) RunAndReturn(run func(context.Context, *engine.BookOrder) ([]*engine.Trade, error)) *MockMatchingService_SubmitOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchingService creates a new instance of MockMatchingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchingService {
	mock := &MockMatchingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
