// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "booker/modules/users/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// GenerateTokenPair provides a mock function with given fields: ctx, userID, email, role
func (_m *MockTokenService) GenerateTokenPair(ctx context.Context, userID string, email string, role string) (string, string, error) {
	ret := _m.Called(ctx, userID, email, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, string, error)); ok {
		return rf(ctx, userID, email, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, userID, email, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) string); ok {
		r1 = rf(ctx, userID, email, role)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, userID, email, role)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenService_GenerateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenPair'
type MockTokenService_GenerateTokenPair_Call struct {
	*mock.Call
}

// GenerateTokenPair is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - email string
//   - role string
func (_e *MockTokenService_Expecter) GenerateTokenPair(ctx interface{}, userID interface{}, email interface{}, role interface{}) *MockTokenService_GenerateTokenPair_Call {
	return &MockTokenService_GenerateTokenPair_Call{Call: _e.mock.On("GenerateTokenPair", ctx, userID, email, role)}
}

func (_c *MockTokenService_GenerateTokenPair_Call) Run(run func(ctx context.Context, userID string, email string, role string)) *MockTokenService_GenerateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTokenService_GenerateTokenPair_Call) Return(accessToken string, refreshToken string, err error) *MockTokenService_GenerateTokenPair_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *MockTokenService_GenerateTokenPair_Call) RunAndReturn(run func(context.Context, string, string, string) (string, string, error)) *MockTokenService_GenerateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserTokens provides a mock function with given fields: ctx, userID
func (_m *MockTokenService) RevokeAllUserTokens(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenService_RevokeAllUserTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserTokens'
type MockTokenService_RevokeAllUserTokens_Call struct {
	*mock.Call
}

// RevokeAllUserTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTokenService_Expecter) RevokeAllUserTokens(ctx interface{}, userID interface{}) *MockTokenService_RevokeAllUserTokens_Call {
	return &MockTokenService_RevokeAllUserTokens_Call{Call: _e.mock.On("RevokeAllUserTokens", ctx, userID)}
}

func (_c *MockTokenService_RevokeAllUserTokens_Call) Run(run func(ctx context.Context, userID string)) *MockTokenService_RevokeAllUserTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenService_RevokeAllUserTokens_Call) Return(_a0 error) *MockTokenService_RevokeAllUserTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenService_RevokeAllUserTokens_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenService_RevokeAllUserTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: ctx, token
func (_m *MockTokenService) ValidateAccessToken(ctx context.Context, token string) (*entities.AccessClaims, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *entities.AccessClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.AccessClaims, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.AccessClaims); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AccessClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenService_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockTokenService_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenService_Expecter) ValidateAccessToken(ctx interface{}, token interface{}) *MockTokenService_ValidateAccessToken_Call {
	return &MockTokenService_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, token)}
}

func (_c *MockTokenService_ValidateAccessToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenService_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenService_ValidateAccessToken_Call) Return(_a0 *entities.AccessClaims, _a1 error) *MockTokenService_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenService_ValidateAccessToken_Call) RunAndReturn(run func(context.Context, string) (*entities.AccessClaims, error)) *MockTokenService_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function with given fields: ctx, token
func (_m *MockTokenService) ValidateRefreshToken(ctx context.Context, token string) (*entities.RefreshClaims, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *entities.RefreshClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.RefreshClaims, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.RefreshClaims); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.RefreshClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenService_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockTokenService_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenService_Expecter) ValidateRefreshToken(ctx interface{}, token interface{}) *MockTokenService_ValidateRefreshToken_Call {
	return &MockTokenService_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", ctx, token)}
}

func (_c *MockTokenService_ValidateRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenService_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenService_ValidateRefreshToken_Call) Return(_a0 *entities.RefreshClaims, _a1 error) *MockTokenService_ValidateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenService_ValidateRefreshToken_Call) RunAndReturn(run func(context.Context, string) (*entities.RefreshClaims, error)) *MockTokenService_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
