// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "booker/modules/order/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMatchingClient is an autogenerated mock type for the MatchingClient type
type MockMatchingClient struct {
	mock.Mock
}

type MockMatchingClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchingClient) EXPECT() *MockMatchingClient_Expecter {
	return &MockMatchingClient_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, pairID, orderID
func (_m *MockMatchingClient) CancelOrder(ctx context.Context, pairID string, orderID string) error {
	ret := _m.Called(ctx, pairID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, pairID, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchingClient_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockMatchingClient_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - pairID string
//   - orderID string
func (_e *MockMatchingClient_Expecter) CancelOrder(ctx interface{}, pairID interface{}, orderID interface{}) *MockMatchingClient_CancelOrder_Call {
	return &MockMatchingClient_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, pairID, orderID)}
}

func (_c *MockMatchingClient_CancelOrder_Call) Run(run func(ctx context.Context, pairID string, orderID string)) *MockMatchingClient_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMatchingClient_CancelOrder_Call) Return(_a0 error) *MockMatchingClient_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchingClient_CancelOrder_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMatchingClient_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitOrder provides a mock function with given fields: ctx, order
func (_m *MockMatchingClient) SubmitOrder(ctx context.Context, order *entities.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SubmitOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchingClient_SubmitOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitOrder'
type MockMatchingClient_SubmitOrder_Call struct {
	*mock.Call
}

// SubmitOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *entities.Order
func (_e *MockMatchingClient_Expecter) SubmitOrder(ctx interface{}, order interface{}) *MockMatchingClient_SubmitOrder_Call {
	return &MockMatchingClient_SubmitOrder_Call{Call: _e.mock.On("SubmitOrder", ctx, order)}
}

func (_c *MockMatchingClient_SubmitOrder_Call) Run(run func(ctx context.Context, order *entities.Order)) *MockMatchingClient_SubmitOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Order))
	})
	return _c
}

func (_c *MockMatchingClient_SubmitOrder_Call) Return(_a0 error) *MockMatchingClient_SubmitOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchingClient_SubmitOrder_Call) RunAndReturn(run func(context.Context, *entities.Order) error) *MockMatchingClient_SubmitOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchingClient creates a new instance of MockMatchingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchingClient {
	mock := &MockMatchingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
