// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"
)

// MockWalletClient is an autogenerated mock type for the WalletClient type
type MockWalletClient struct {
	mock.Mock
}

type MockWalletClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletClient) EXPECT() *MockWalletClient_Expecter {
	return &MockWalletClient_Expecter{mock: &_m.Mock}
}

// HoldBalance provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockWalletClient) HoldBalance(ctx context.Context, userID string, assetID string, amount decimal.Decimal) error {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for HoldBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletClient_HoldBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HoldBalance'
type MockWalletClient_HoldBalance_Call struct {
	*mock.Call
}

// HoldBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockWalletClient_Expecter) HoldBalance(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockWalletClient_HoldBalance_Call {
	return &MockWalletClient_HoldBalance_Call{Call: _e.mock.On("HoldBalance", ctx, userID, assetID, amount)}
}

func (_c *MockWalletClient_HoldBalance_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockWalletClient_HoldBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockWalletClient_HoldBalance_Call) Return(_a0 error) *MockWalletClient_HoldBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletClient_HoldBalance_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) error) *MockWalletClient_HoldBalance_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseBalance provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockWalletClient) ReleaseBalance(ctx context.Context, userID string, assetID string, amount decimal.Decimal) error {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletClient_ReleaseBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseBalance'
type MockWalletClient_ReleaseBalance_Call struct {
	*mock.Call
}

// ReleaseBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockWalletClient_Expecter) ReleaseBalance(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockWalletClient_ReleaseBalance_Call {
	return &MockWalletClient_ReleaseBalance_Call{Call: _e.mock.On("ReleaseBalance", ctx, userID, assetID, amount)}
}

func (_c *MockWalletClient_ReleaseBalance_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockWalletClient_ReleaseBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockWalletClient_ReleaseBalance_Call) Return(_a0 error) *MockWalletClient_ReleaseBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletClient_ReleaseBalance_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) error) *MockWalletClient_ReleaseBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletClient creates a new instance of MockWalletClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletClient {
	mock := &MockWalletClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
