// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dto "booker/modules/order/application/dto"
	context "context"

	decimal "github.com/shopspring/decimal"

	entities "booker/modules/order/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, userID, orderID
func (_m *MockOrderService) CancelOrder(ctx context.Context, userID string, orderID string) (*entities.Order, error) {
	ret := _m.Called(ctx, userID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 *entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.Order, error)); ok {
		return rf(ctx, userID, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.Order); ok {
		r0 = rf(ctx, userID, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockOrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - orderID string
func (_e *MockOrderService_Expecter) CancelOrder(ctx interface{}, userID interface{}, orderID interface{}) *MockOrderService_CancelOrder_Call {
	return &MockOrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, userID, orderID)}
}

func (_c *MockOrderService_CancelOrder_Call) Run(run func(ctx context.Context, userID string, orderID string)) *MockOrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrderService_CancelOrder_Call) Return(_a0 *entities.Order, _a1 error) *MockOrderService_CancelOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_CancelOrder_Call) RunAndReturn(run func(context.Context, string, string) (*entities.Order, error)) *MockOrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, userID, req
func (_m *MockOrderService) CreateOrder(ctx context.Context, userID string, req *dto.CreateOrderDTO) (*entities.Order, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.CreateOrderDTO) (*entities.Order, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.CreateOrderDTO) *entities.Order); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.CreateOrderDTO) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *dto.CreateOrderDTO
func (_e *MockOrderService_Expecter) CreateOrder(ctx interface{}, userID interface{}, req interface{}) *MockOrderService_CreateOrder_Call {
	return &MockOrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userID, req)}
}

func (_c *MockOrderService_CreateOrder_Call) Run(run func(ctx context.Context, userID string, req *dto.CreateOrderDTO)) *MockOrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*dto.CreateOrderDTO))
	})
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) Return(_a0 *entities.Order, _a1 error) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) RunAndReturn(run func(context.Context, string, *dto.CreateOrderDTO) (*entities.Order, error)) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, userID, orderID
func (_m *MockOrderService) GetOrder(ctx context.Context, userID string, orderID string) (*entities.Order, error) {
	ret := _m.Called(ctx, userID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.Order, error)); ok {
		return rf(ctx, userID, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.Order); ok {
		r0 = rf(ctx, userID, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - orderID string
func (_e *MockOrderService_Expecter) GetOrder(ctx interface{}, userID interface{}, orderID interface{}) *MockOrderService_GetOrder_Call {
	return &MockOrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, userID, orderID)}
}

func (_c *MockOrderService_GetOrder_Call) Run(run func(ctx context.Context, userID string, orderID string)) *MockOrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrderService_GetOrder_Call) Return(_a0 *entities.Order, _a1 error) *MockOrderService_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_GetOrder_Call) RunAndReturn(run func(context.Context, string, string) (*entities.Order, error)) *MockOrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrders provides a mock function with given fields: ctx, userID, req
func (_m *MockOrderService) ListOrders(ctx context.Context, userID string, req *dto.ListOrdersDTO) ([]*entities.Order, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for ListOrders")
	}

	var r0 []*entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.ListOrdersDTO) ([]*entities.Order, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.ListOrdersDTO) []*entities.Order); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.ListOrdersDTO) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_ListOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrders'
type MockOrderService_ListOrders_Call struct {
	*mock.Call
}

// ListOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *dto.ListOrdersDTO
func (_e *MockOrderService_Expecter) ListOrders(ctx interface{}, userID interface{}, req interface{}) *MockOrderService_ListOrders_Call {
	return &MockOrderService_ListOrders_Call{Call: _e.mock.On("ListOrders", ctx, userID, req)}
}

func (_c *MockOrderService_ListOrders_Call) Run(run func(ctx context.Context, userID string, req *dto.ListOrdersDTO)) *MockOrderService_ListOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*dto.ListOrdersDTO))
	})
	return _c
}

func (_c *MockOrderService_ListOrders_Call) Return(_a0 []*entities.Order, _a1 error) *MockOrderService_ListOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_ListOrders_Call) RunAndReturn(run func(context.Context, string, *dto.ListOrdersDTO) ([]*entities.Order, error)) *MockOrderService_ListOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderFill provides a mock function with given fields: ctx, orderID, filledQty, status
func (_m *MockOrderService) UpdateOrderFill(ctx context.Context, orderID string, filledQty decimal.Decimal, status string) (*entities.Order, error) {
	ret := _m.Called(ctx, orderID, filledQty, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderFill")
	}

	var r0 *entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, decimal.Decimal, string) (*entities.Order, error)); ok {
		return rf(ctx, orderID, filledQty, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, decimal.Decimal, string) *entities.Order); ok {
		r0 = rf(ctx, orderID, filledQty, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, decimal.Decimal, string) error); ok {
		r1 = rf(ctx, orderID, filledQty, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_UpdateOrderFill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderFill'
type MockOrderService_UpdateOrderFill_Call struct {
	*mock.Call
}

// UpdateOrderFill is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - filledQty decimal.Decimal
//   - status string
func (_e *MockOrderService_Expecter) UpdateOrderFill(ctx interface{}, orderID interface{}, filledQty interface{}, status interface{}) *MockOrderService_UpdateOrderFill_Call {
	return &MockOrderService_UpdateOrderFill_Call{Call: _e.mock.On("UpdateOrderFill", ctx, orderID, filledQty, status)}
}

func (_c *MockOrderService_UpdateOrderFill_Call) Run(run func(ctx context.Context, orderID string, filledQty decimal.Decimal, status string)) *MockOrderService_UpdateOrderFill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(decimal.Decimal), args[3].(string))
	})
	return _c
}

func (_c *MockOrderService_UpdateOrderFill_Call) Return(_a0 *entities.Order, _a1 error) *MockOrderService_UpdateOrderFill_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_UpdateOrderFill_Call) RunAndReturn(run func(context.Context, string, decimal.Decimal, string) (*entities.Order, error)) *MockOrderService_UpdateOrderFill_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
