// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "booker/modules/order/domain/entities"
	context "context"

	decimal "github.com/shopspring/decimal"

	interfaces "booker/modules/order/domain/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, id, userID
func (_m *MockOrderRepository) Cancel(ctx context.Context, id string, userID string) (*entities.Order, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 *entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.Order, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.Order); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockOrderRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockOrderRepository_Expecter) Cancel(ctx interface{}, id interface{}, userID interface{}) *MockOrderRepository_Cancel_Call {
	return &MockOrderRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id, userID)}
}

func (_c *MockOrderRepository_Cancel_Call) Run(run func(ctx context.Context, id string, userID string)) *MockOrderRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrderRepository_Cancel_Call) Return(_a0 *entities.Order, _a1 error) *MockOrderRepository_Cancel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_Cancel_Call) RunAndReturn(run func(context.Context, string, string) (*entities.Order, error)) *MockOrderRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, order
func (_m *MockOrderRepository) Create(ctx context.Context, order *entities.Order) (*entities.Order, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Order) (*entities.Order, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Order) *entities.Order); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order *entities.Order
func (_e *MockOrderRepository_Expecter) Create(ctx interface{}, order interface{}) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(ctx context.Context, order *entities.Order)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Order))
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(_a0 *entities.Order, _a1 error) *MockOrderRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.Order) (*entities.Order, error)) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockOrderRepository) GetByID(ctx context.Context, id string) (*entities.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrderRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrderRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockOrderRepository_GetByID_Call {
	return &MockOrderRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockOrderRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockOrderRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrderRepository_GetByID_Call) Return(_a0 *entities.Order, _a1 error) *MockOrderRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*entities.Order, error)) *MockOrderRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDAndUser provides a mock function with given fields: ctx, id, userID
func (_m *MockOrderRepository) GetByIDAndUser(ctx context.Context, id string, userID string) (*entities.Order, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDAndUser")
	}

	var r0 *entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.Order, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.Order); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_GetByIDAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDAndUser'
type MockOrderRepository_GetByIDAndUser_Call struct {
	*mock.Call
}

// GetByIDAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockOrderRepository_Expecter) GetByIDAndUser(ctx interface{}, id interface{}, userID interface{}) *MockOrderRepository_GetByIDAndUser_Call {
	return &MockOrderRepository_GetByIDAndUser_Call{Call: _e.mock.On("GetByIDAndUser", ctx, id, userID)}
}

func (_c *MockOrderRepository_GetByIDAndUser_Call) Run(run func(ctx context.Context, id string, userID string)) *MockOrderRepository_GetByIDAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrderRepository_GetByIDAndUser_Call) Return(_a0 *entities.Order, _a1 error) *MockOrderRepository_GetByIDAndUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_GetByIDAndUser_Call) RunAndReturn(run func(context.Context, string, string) (*entities.Order, error)) *MockOrderRepository_GetByIDAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradingPair provides a mock function with given fields: ctx, pairID
func (_m *MockOrderRepository) GetTradingPair(ctx context.Context, pairID string) (*interfaces.TradingPair, error) {
	ret := _m.Called(ctx, pairID)

	if len(ret) == 0 {
		panic("no return value specified for GetTradingPair")
	}

	var r0 *interfaces.TradingPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.TradingPair, error)); ok {
		return rf(ctx, pairID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.TradingPair); ok {
		r0 = rf(ctx, pairID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.TradingPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pairID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_GetTradingPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradingPair'
type MockOrderRepository_GetTradingPair_Call struct {
	*mock.Call
}

// GetTradingPair is a helper method to define mock.On call
//   - ctx context.Context
//   - pairID string
func (_e *MockOrderRepository_Expecter) GetTradingPair(ctx interface{}, pairID interface{}) *MockOrderRepository_GetTradingPair_Call {
	return &MockOrderRepository_GetTradingPair_Call{Call: _e.mock.On("GetTradingPair", ctx, pairID)}
}

func (_c *MockOrderRepository_GetTradingPair_Call) Run(run func(ctx context.Context, pairID string)) *MockOrderRepository_GetTradingPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrderRepository_GetTradingPair_Call) Return(_a0 *interfaces.TradingPair, _a1 error) *MockOrderRepository_GetTradingPair_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_GetTradingPair_Call) RunAndReturn(run func(context.Context, string) (*interfaces.TradingPair, error)) *MockOrderRepository_GetTradingPair_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, pairID, status, limit, offset
func (_m *MockOrderRepository) List(ctx context.Context, userID string, pairID *string, status *string, limit int32, offset int32) ([]*entities.Order, error) {
	ret := _m.Called(ctx, userID, pairID, status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, int32, int32) ([]*entities.Order, error)); ok {
		return rf(ctx, userID, pairID, status, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, int32, int32) []*entities.Order); ok {
		r0 = rf(ctx, userID, pairID, status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *string, int32, int32) error); ok {
		r1 = rf(ctx, userID, pairID, status, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockOrderRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - pairID *string
//   - status *string
//   - limit int32
//   - offset int32
func (_e *MockOrderRepository_Expecter) List(ctx interface{}, userID interface{}, pairID interface{}, status interface{}, limit interface{}, offset interface{}) *MockOrderRepository_List_Call {
	return &MockOrderRepository_List_Call{Call: _e.mock.On("List", ctx, userID, pairID, status, limit, offset)}
}

func (_c *MockOrderRepository_List_Call) Run(run func(ctx context.Context, userID string, pairID *string, status *string, limit int32, offset int32)) *MockOrderRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string), args[4].(int32), args[5].(int32))
	})
	return _c
}

func (_c *MockOrderRepository_List_Call) Return(_a0 []*entities.Order, _a1 error) *MockOrderRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_List_Call) RunAndReturn(run func(context.Context, string, *string, *string, int32, int32) ([]*entities.Order, error)) *MockOrderRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFilledQty provides a mock function with given fields: ctx, id, filledQty, status
func (_m *MockOrderRepository) UpdateFilledQty(ctx context.Context, id string, filledQty decimal.Decimal, status string) (*entities.Order, error) {
	ret := _m.Called(ctx, id, filledQty, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFilledQty")
	}

	var r0 *entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, decimal.Decimal, string) (*entities.Order, error)); ok {
		return rf(ctx, id, filledQty, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, decimal.Decimal, string) *entities.Order); ok {
		r0 = rf(ctx, id, filledQty, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, decimal.Decimal, string) error); ok {
		r1 = rf(ctx, id, filledQty, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_UpdateFilledQty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFilledQty'
type MockOrderRepository_UpdateFilledQty_Call struct {
	*mock.Call
}

// UpdateFilledQty is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - filledQty decimal.Decimal
//   - status string
func (_e *MockOrderRepository_Expecter) UpdateFilledQty(ctx interface{}, id interface{}, filledQty interface{}, status interface{}) *MockOrderRepository_UpdateFilledQty_Call {
	return &MockOrderRepository_UpdateFilledQty_Call{Call: _e.mock.On("UpdateFilledQty", ctx, id, filledQty, status)}
}

func (_c *MockOrderRepository_UpdateFilledQty_Call) Run(run func(ctx context.Context, id string, filledQty decimal.Decimal, status string)) *MockOrderRepository_UpdateFilledQty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(decimal.Decimal), args[3].(string))
	})
	return _c
}

func (_c *MockOrderRepository_UpdateFilledQty_Call) Return(_a0 *entities.Order, _a1 error) *MockOrderRepository_UpdateFilledQty_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_UpdateFilledQty_Call) RunAndReturn(run func(context.Context, string, decimal.Decimal, string) (*entities.Order, error)) *MockOrderRepository_UpdateFilledQty_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
