// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "booker/modules/wallet/domain/entities"
	context "context"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"
)

// MockWalletService is an autogenerated mock type for the WalletService type
type MockWalletService struct {
	mock.Mock
}

type MockWalletService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletService) EXPECT() *MockWalletService_Expecter {
	return &MockWalletService_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockWalletService) Deposit(ctx context.Context, userID string, assetID string, amount decimal.Decimal) (*entities.Wallet, error) {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 *entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)); ok {
		return rf(ctx, userID, assetID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) *entities.Wallet); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, userID, assetID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type MockWalletService_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockWalletService_Expecter) Deposit(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockWalletService_Deposit_Call {
	return &MockWalletService_Deposit_Call{Call: _e.mock.On("Deposit", ctx, userID, assetID, amount)}
}

func (_c *MockWalletService_Deposit_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockWalletService_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockWalletService_Deposit_Call) Return(_a0 *entities.Wallet, _a1 error) *MockWalletService_Deposit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_Deposit_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)) *MockWalletService_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function with given fields: ctx, userID, assetID
func (_m *MockWalletService) GetBalance(ctx context.Context, userID string, assetID string) (*entities.Wallet, error) {
	ret := _m.Called(ctx, userID, assetID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.Wallet, error)); ok {
		return rf(ctx, userID, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.Wallet); ok {
		r0 = rf(ctx, userID, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockWalletService_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
func (_e *MockWalletService_Expecter) GetBalance(ctx interface{}, userID interface{}, assetID interface{}) *MockWalletService_GetBalance_Call {
	return &MockWalletService_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID, assetID)}
}

func (_c *MockWalletService_GetBalance_Call) Run(run func(ctx context.Context, userID string, assetID string)) *MockWalletService_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockWalletService_GetBalance_Call) Return(_a0 *entities.Wallet, _a1 error) *MockWalletService_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_GetBalance_Call) RunAndReturn(run func(context.Context, string, string) (*entities.Wallet, error)) *MockWalletService_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalances provides a mock function with given fields: ctx, userID
func (_m *MockWalletService) GetBalances(ctx context.Context, userID string) ([]*entities.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalances")
	}

	var r0 []*entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entities.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entities.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_GetBalances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalances'
type MockWalletService_GetBalances_Call struct {
	*mock.Call
}

// GetBalances is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockWalletService_Expecter) GetBalances(ctx interface{}, userID interface{}) *MockWalletService_GetBalances_Call {
	return &MockWalletService_GetBalances_Call{Call: _e.mock.On("GetBalances", ctx, userID)}
}

func (_c *MockWalletService_GetBalances_Call) Run(run func(ctx context.Context, userID string)) *MockWalletService_GetBalances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWalletService_GetBalances_Call) Return(_a0 []*entities.Wallet, _a1 error) *MockWalletService_GetBalances_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_GetBalances_Call) RunAndReturn(run func(context.Context, string) ([]*entities.Wallet, error)) *MockWalletService_GetBalances_Call {
	_c.Call.Return(run)
	return _c
}

// HoldBalance provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockWalletService) HoldBalance(ctx context.Context, userID string, assetID string, amount decimal.Decimal) (*entities.Wallet, error) {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for HoldBalance")
	}

	var r0 *entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)); ok {
		return rf(ctx, userID, assetID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) *entities.Wallet); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, userID, assetID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_HoldBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HoldBalance'
type MockWalletService_HoldBalance_Call struct {
	*mock.Call
}

// HoldBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockWalletService_Expecter) HoldBalance(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockWalletService_HoldBalance_Call {
	return &MockWalletService_HoldBalance_Call{Call: _e.mock.On("HoldBalance", ctx, userID, assetID, amount)}
}

func (_c *MockWalletService_HoldBalance_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockWalletService_HoldBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockWalletService_HoldBalance_Call) Return(_a0 *entities.Wallet, _a1 error) *MockWalletService_HoldBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_HoldBalance_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)) *MockWalletService_HoldBalance_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseBalance provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockWalletService) ReleaseBalance(ctx context.Context, userID string, assetID string, amount decimal.Decimal) (*entities.Wallet, error) {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseBalance")
	}

	var r0 *entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)); ok {
		return rf(ctx, userID, assetID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) *entities.Wallet); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, userID, assetID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_ReleaseBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseBalance'
type MockWalletService_ReleaseBalance_Call struct {
	*mock.Call
}

// ReleaseBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockWalletService_Expecter) ReleaseBalance(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockWalletService_ReleaseBalance_Call {
	return &MockWalletService_ReleaseBalance_Call{Call: _e.mock.On("ReleaseBalance", ctx, userID, assetID, amount)}
}

func (_c *MockWalletService_ReleaseBalance_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockWalletService_ReleaseBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockWalletService_ReleaseBalance_Call) Return(_a0 *entities.Wallet, _a1 error) *MockWalletService_ReleaseBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_ReleaseBalance_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)) *MockWalletService_ReleaseBalance_Call {
	_c.Call.Return(run)
	return _c
}

// SettleTrade provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockWalletService) SettleTrade(ctx context.Context, userID string, assetID string, amount decimal.Decimal) (*entities.Wallet, error) {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for SettleTrade")
	}

	var r0 *entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)); ok {
		return rf(ctx, userID, assetID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) *entities.Wallet); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, userID, assetID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_SettleTrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SettleTrade'
type MockWalletService_SettleTrade_Call struct {
	*mock.Call
}

// SettleTrade is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockWalletService_Expecter) SettleTrade(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockWalletService_SettleTrade_Call {
	return &MockWalletService_SettleTrade_Call{Call: _e.mock.On("SettleTrade", ctx, userID, assetID, amount)}
}

func (_c *MockWalletService_SettleTrade_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockWalletService_SettleTrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockWalletService_SettleTrade_Call) Return(_a0 *entities.Wallet, _a1 error) *MockWalletService_SettleTrade_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_SettleTrade_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)) *MockWalletService_SettleTrade_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockWalletService) Withdraw(ctx context.Context, userID string, assetID string, amount decimal.Decimal) (*entities.Wallet, error) {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 *entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)); ok {
		return rf(ctx, userID, assetID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) *entities.Wallet); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, userID, assetID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockWalletService_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockWalletService_Expecter) Withdraw(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockWalletService_Withdraw_Call {
	return &MockWalletService_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, assetID, amount)}
}

func (_c *MockWalletService_Withdraw_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockWalletService_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockWalletService_Withdraw_Call) Return(_a0 *entities.Wallet, _a1 error) *MockWalletService_Withdraw_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_Withdraw_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)) *MockWalletService_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletService creates a new instance of MockWalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletService {
	mock := &MockWalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
