// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "booker/modules/wallet/domain/entities"
	context "context"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"
)

// MockWalletRepository is an autogenerated mock type for the WalletRepository type
type MockWalletRepository struct {
	mock.Mock
}

type MockWalletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletRepository) EXPECT() *MockWalletRepository_Expecter {
	return &MockWalletRepository_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockWalletRepository) Deposit(ctx context.Context, userID string, assetID string, amount decimal.Decimal) (*entities.Wallet, error) {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 *entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)); ok {
		return rf(ctx, userID, assetID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) *entities.Wallet); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, userID, assetID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type MockWalletRepository_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockWalletRepository_Expecter) Deposit(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockWalletRepository_Deposit_Call {
	return &MockWalletRepository_Deposit_Call{Call: _e.mock.On("Deposit", ctx, userID, assetID, amount)}
}

func (_c *MockWalletRepository_Deposit_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockWalletRepository_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockWalletRepository_Deposit_Call) Return(_a0 *entities.Wallet, _a1 error) *MockWalletRepository_Deposit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_Deposit_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)) *MockWalletRepository_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockWalletRepository) GetByUserID(ctx context.Context, userID string) ([]*entities.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entities.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entities.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockWalletRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockWalletRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockWalletRepository_GetByUserID_Call {
	return &MockWalletRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockWalletRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockWalletRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWalletRepository_GetByUserID_Call) Return(_a0 []*entities.Wallet, _a1 error) *MockWalletRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) ([]*entities.Wallet, error)) *MockWalletRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreate provides a mock function with given fields: ctx, userID, assetID
func (_m *MockWalletRepository) GetOrCreate(ctx context.Context, userID string, assetID string) (*entities.Wallet, error) {
	ret := _m.Called(ctx, userID, assetID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.Wallet, error)); ok {
		return rf(ctx, userID, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.Wallet); ok {
		r0 = rf(ctx, userID, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type MockWalletRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
func (_e *MockWalletRepository_Expecter) GetOrCreate(ctx interface{}, userID interface{}, assetID interface{}) *MockWalletRepository_GetOrCreate_Call {
	return &MockWalletRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, userID, assetID)}
}

func (_c *MockWalletRepository_GetOrCreate_Call) Run(run func(ctx context.Context, userID string, assetID string)) *MockWalletRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockWalletRepository_GetOrCreate_Call) Return(_a0 *entities.Wallet, _a1 error) *MockWalletRepository_GetOrCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_GetOrCreate_Call) RunAndReturn(run func(context.Context, string, string) (*entities.Wallet, error)) *MockWalletRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// Hold provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockWalletRepository) Hold(ctx context.Context, userID string, assetID string, amount decimal.Decimal) (*entities.Wallet, error) {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Hold")
	}

	var r0 *entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)); ok {
		return rf(ctx, userID, assetID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) *entities.Wallet); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, userID, assetID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_Hold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hold'
type MockWalletRepository_Hold_Call struct {
	*mock.Call
}

// Hold is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockWalletRepository_Expecter) Hold(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockWalletRepository_Hold_Call {
	return &MockWalletRepository_Hold_Call{Call: _e.mock.On("Hold", ctx, userID, assetID, amount)}
}

func (_c *MockWalletRepository_Hold_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockWalletRepository_Hold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockWalletRepository_Hold_Call) Return(_a0 *entities.Wallet, _a1 error) *MockWalletRepository_Hold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_Hold_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)) *MockWalletRepository_Hold_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockWalletRepository) Release(ctx context.Context, userID string, assetID string, amount decimal.Decimal) (*entities.Wallet, error) {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 *entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)); ok {
		return rf(ctx, userID, assetID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) *entities.Wallet); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, userID, assetID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockWalletRepository_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockWalletRepository_Expecter) Release(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockWalletRepository_Release_Call {
	return &MockWalletRepository_Release_Call{Call: _e.mock.On("Release", ctx, userID, assetID, amount)}
}

func (_c *MockWalletRepository_Release_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockWalletRepository_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockWalletRepository_Release_Call) Return(_a0 *entities.Wallet, _a1 error) *MockWalletRepository_Release_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_Release_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)) *MockWalletRepository_Release_Call {
	_c.Call.Return(run)
	return _c
}

// Settle provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockWalletRepository) Settle(ctx context.Context, userID string, assetID string, amount decimal.Decimal) (*entities.Wallet, error) {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Settle")
	}

	var r0 *entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)); ok {
		return rf(ctx, userID, assetID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) *entities.Wallet); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, userID, assetID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_Settle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Settle'
type MockWalletRepository_Settle_Call struct {
	*mock.Call
}

// Settle is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockWalletRepository_Expecter) Settle(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockWalletRepository_Settle_Call {
	return &MockWalletRepository_Settle_Call{Call: _e.mock.On("Settle", ctx, userID, assetID, amount)}
}

func (_c *MockWalletRepository_Settle_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockWalletRepository_Settle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockWalletRepository_Settle_Call) Return(_a0 *entities.Wallet, _a1 error) *MockWalletRepository_Settle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_Settle_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)) *MockWalletRepository_Settle_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, userID, assetID, amount
func (_m *MockWalletRepository) Withdraw(ctx context.Context, userID string, assetID string, amount decimal.Decimal) (*entities.Wallet, error) {
	ret := _m.Called(ctx, userID, assetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 *entities.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)); ok {
		return rf(ctx, userID, assetID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) *entities.Wallet); ok {
		r0 = rf(ctx, userID, assetID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, userID, assetID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockWalletRepository_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - assetID string
//   - amount decimal.Decimal
func (_e *MockWalletRepository_Expecter) Withdraw(ctx interface{}, userID interface{}, assetID interface{}, amount interface{}) *MockWalletRepository_Withdraw_Call {
	return &MockWalletRepository_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, assetID, amount)}
}

func (_c *MockWalletRepository_Withdraw_Call) Run(run func(ctx context.Context, userID string, assetID string, amount decimal.Decimal)) *MockWalletRepository_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *MockWalletRepository_Withdraw_Call) Return(_a0 *entities.Wallet, _a1 error) *MockWalletRepository_Withdraw_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_Withdraw_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) (*entities.Wallet, error)) *MockWalletRepository_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletRepository creates a new instance of MockWalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletRepository {
	mock := &MockWalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
